// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/approve-request": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Aprova ou rejeita uma solicitação de registo (apenas contabilistas/admin)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Aprovar/rejeitar solicitação",
                "parameters": [
                    {
                        "description": "Dados de aprovação",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ApprovalRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/admin/clients": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Lista todos os clientes com status aprovado (apenas contabilista/admin)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Listar clientes aprovados",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/admin/clients/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Atualiza dados pessoais de um cliente (apenas contabilista/admin)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Atualizar dados de cliente",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do cliente",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Dados para atualizar",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AdminUpdateClientDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Elimina um cliente e a sua empresa (apenas contabilista/admin)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Eliminar cliente",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do cliente",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/admin/clients/{id}/company": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Atualiza dados da empresa de um cliente (apenas contabilista/admin)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Atualizar empresa do cliente",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do cliente",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Dados da empresa para atualizar",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AdminUpdateCompanyDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/admin/pending-requests": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Lista todas as solicitações de registo pendentes (apenas contabilistas/admin)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Listar solicitações pendentes",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/admin/requests": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Lista todos os pedidos de registo pendentes para aprovação",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Listar pedidos de registo pendentes",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/admin/requests/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Obtém detalhes completos de um pedido de registo específico",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Detalhes de um pedido de registo",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do pedido",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/admin/users": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Lista todos os utilizadores do sistema (apenas admin/contabilista)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Listar todos os utilizadores",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/admin/users/count": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Conta quantos utilizadores existem por status e role",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Contar utilizadores",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/admin/users/simple": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Lista utilizadores sem relacionamentos para debug",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Listar utilizadores (simples)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/admin/users/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Obtém detalhes completos de um utilizador",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Detalhes de um utilizador",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do utilizador",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/admin/users/{id}/status": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Bloqueia/desbloqueia utilizador (apenas admin)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Alterar status de utilizador",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do utilizador",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Novo status",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateUserStatusDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Login com username e password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Entrar",
                "parameters": [
                    {
                        "description": "Username e password",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.AuthResponse"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Remove token do lado do cliente",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Logout do utilizador",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Cria uma nova solicitação de registo para aprovação da contabilista",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Registo de novo cliente",
                "parameters": [
                    {
                        "description": "Dados de registo completos",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RegistrationRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/auth/register-direct": {
            "post": {
                "description": "Regista novo utilizador diretamente (para uso interno)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Criar conta diretamente",
                "parameters": [
                    {
                        "description": "Dados de registo",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.AuthResponse"
                        }
                    }
                }
            }
        },
        "/client/company": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Obtém dados da empresa do cliente logado",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "client"
                ],
                "summary": "Dados da empresa do cliente",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Atualiza dados da empresa do cliente (campos limitados)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "client"
                ],
                "summary": "Atualizar dados da empresa",
                "parameters": [
                    {
                        "description": "Dados a atualizar",
                        "name": "company",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateCompanyDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/client/complete-company-data": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Completa dados da empresa adicionais após aprovação",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "client"
                ],
                "summary": "Completar dados da empresa",
                "parameters": [
                    {
                        "description": "Dados da empresa completos",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CompleteCompanyDataDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/client/complete-user-data": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Completa dados pessoais adicionais após aprovação",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "client"
                ],
                "summary": "Completar dados pessoais",
                "parameters": [
                    {
                        "description": "Dados pessoais completos",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CompleteUserDataDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/client/profile": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Obtém perfil do cliente logado",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "client"
                ],
                "summary": "Perfil do cliente",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Atualiza dados pessoais do cliente",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "client"
                ],
                "summary": "Atualizar perfil do cliente",
                "parameters": [
                    {
                        "description": "Dados a atualizar",
                        "name": "profile",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateProfileDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/client/requests": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Lista todas as solicitações do cliente logado",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "client"
                ],
                "summary": "Histórico de solicitações do cliente",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/info": {
            "get": {
                "description": "Como usar a API e autenticação",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "info"
                ],
                "summary": "Informações da API",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/profile": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Obtém dados do utilizador logado (requer token no header Authorization)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Meu perfil",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.AdminUpdateClientDTO": {
            "type": "object",
            "properties": {
                "billing_software": {
                    "type": "string"
                },
                "citizen_card_expiry": {
                    "type": "string"
                },
                "citizen_card_number": {
                    "type": "string"
                },
                "date_of_birth": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "fiscal_address": {
                    "description": "Morada fiscal",
                    "type": "string"
                },
                "fiscal_city": {
                    "type": "string"
                },
                "fiscal_county": {
                    "type": "string"
                },
                "fiscal_district": {
                    "type": "string"
                },
                "fiscal_postal_code": {
                    "type": "string"
                },
                "fixed_phone": {
                    "type": "string"
                },
                "marital_status": {
                    "type": "string"
                },
                "name": {
                    "description": "Dados pessoais que admin pode editar",
                    "type": "string"
                },
                "nif": {
                    "type": "string"
                },
                "official_email": {
                    "description": "Configurações",
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "preferred_contact_hours": {
                    "type": "string"
                },
                "preferred_format": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "models.AdminUpdateCompanyDTO": {
            "type": "object",
            "properties": {
                "accounting_regime": {
                    "description": "Regimes",
                    "type": "string"
                },
                "address": {
                    "description": "Morada da empresa",
                    "type": "string"
                },
                "annual_revenue": {
                    "type": "number"
                },
                "bank_name": {
                    "type": "string"
                },
                "bic": {
                    "type": "string"
                },
                "business_activity": {
                    "description": "Operacionais",
                    "type": "string"
                },
                "cae": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "company_name": {
                    "type": "string"
                },
                "corporate_object": {
                    "type": "string"
                },
                "county": {
                    "type": "string"
                },
                "district": {
                    "type": "string"
                },
                "estimated_revenue": {
                    "type": "number"
                },
                "founding_date": {
                    "type": "string"
                },
                "has_stock": {
                    "type": "boolean"
                },
                "iban": {
                    "type": "string"
                },
                "legal_form": {
                    "type": "string"
                },
                "main_clients": {
                    "type": "string"
                },
                "main_suppliers": {
                    "type": "string"
                },
                "monthly_invoices": {
                    "type": "integer"
                },
                "nipc": {
                    "type": "string"
                },
                "number_employees": {
                    "type": "integer"
                },
                "postal_code": {
                    "type": "string"
                },
                "report_frequency": {
                    "type": "string"
                },
                "share_capital": {
                    "description": "Dados financeiros",
                    "type": "number"
                },
                "trade_name": {
                    "type": "string"
                },
                "vat_regime": {
                    "type": "string"
                }
            }
        },
        "models.ApprovalRequestDTO": {
            "type": "object",
            "required": [
                "request_id",
                "status"
            ],
            "properties": {
                "request_id": {
                    "type": "integer",
                    "example": 1
                },
                "review_notes": {
                    "type": "string",
                    "example": "Documentação em ordem"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "approved",
                        "rejected"
                    ],
                    "example": "approved"
                }
            }
        },
        "models.AuthResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                },
                "user": {
                    "$ref": "#/definitions/models.User"
                }
            }
        },
        "models.Company": {
            "type": "object",
            "properties": {
                "accounting_regime": {
                    "type": "string"
                },
                "address": {
                    "type": "string"
                },
                "annual_revenue": {
                    "description": "Dados operacionais",
                    "type": "number"
                },
                "bank_name": {
                    "description": "Informação bancária",
                    "type": "string"
                },
                "bic": {
                    "type": "string"
                },
                "business_activity": {
                    "type": "string"
                },
                "cae": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "company_name": {
                    "description": "Dados copiados da RegistrationRequest após aprovação",
                    "type": "string"
                },
                "corporate_object": {
                    "type": "string"
                },
                "country": {
                    "type": "string"
                },
                "county": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "district": {
                    "type": "string"
                },
                "estimated_revenue": {
                    "type": "number"
                },
                "founding_date": {
                    "type": "string"
                },
                "group_start_date": {
                    "type": "string"
                },
                "has_stock": {
                    "type": "boolean"
                },
                "iban": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "legal_form": {
                    "type": "string"
                },
                "main_clients": {
                    "type": "string"
                },
                "main_suppliers": {
                    "type": "string"
                },
                "monthly_invoices": {
                    "type": "integer"
                },
                "nipc": {
                    "type": "string"
                },
                "number_employees": {
                    "type": "integer"
                },
                "postal_code": {
                    "type": "string"
                },
                "registration_request": {
                    "$ref": "#/definitions/models.RegistrationRequest"
                },
                "share_capital": {
                    "type": "number"
                },
                "status": {
                    "type": "string"
                },
                "trade_name": {
                    "description": "Dados completos",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user": {
                    "description": "Relacionamentos",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.User"
                        }
                    ]
                },
                "user_id": {
                    "description": "One-to-One com User",
                    "type": "integer"
                },
                "vat_regime": {
                    "type": "string"
                }
            }
        },
        "models.CompleteCompanyDataDTO": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "example": "Rua das Flores, 123"
                },
                "annual_revenue": {
                    "type": "number",
                    "example": 100000
                },
                "bank_name": {
                    "type": "string",
                    "example": "Banco Comercial Português"
                },
                "bic": {
                    "type": "string",
                    "example": "BCOMPTPL"
                },
                "city": {
                    "type": "string",
                    "example": "Lisboa"
                },
                "corporate_object": {
                    "type": "string",
                    "example": "Prestação de serviços de consultoria"
                },
                "county": {
                    "type": "string",
                    "example": "Lisboa"
                },
                "district": {
                    "type": "string",
                    "example": "Lisboa"
                },
                "group_start_date": {
                    "type": "string",
                    "example": "2024-01-01"
                },
                "has_stock": {
                    "type": "boolean",
                    "example": false
                },
                "iban": {
                    "type": "string",
                    "example": "PT50000201231234567890154"
                },
                "main_clients": {
                    "type": "string",
                    "example": "Cliente A, Cliente B"
                },
                "main_suppliers": {
                    "type": "string",
                    "example": "Fornecedor X, Fornecedor Y"
                },
                "postal_code": {
                    "type": "string",
                    "example": "1000-001"
                },
                "share_capital": {
                    "type": "number",
                    "example": 5000
                },
                "trade_name": {
                    "type": "string",
                    "example": "Silva Consultoria"
                }
            }
        },
        "models.CompleteUserDataDTO": {
            "type": "object",
            "properties": {
                "billing_software": {
                    "type": "string",
                    "example": "Moloni"
                },
                "citizen_card_expiry": {
                    "type": "string",
                    "example": "2030-12-31"
                },
                "citizen_card_number": {
                    "type": "string",
                    "example": "12345678"
                },
                "e_fatura_password": {
                    "type": "string",
                    "example": "password123"
                },
                "e_fatura_user": {
                    "type": "string",
                    "example": "123456789"
                },
                "fiscal_county": {
                    "type": "string",
                    "example": "Lisboa"
                },
                "fiscal_district": {
                    "type": "string",
                    "example": "Lisboa"
                },
                "fixed_phone": {
                    "type": "string",
                    "example": "213456789"
                },
                "marital_status": {
                    "type": "string",
                    "example": "Solteiro"
                },
                "official_email": {
                    "type": "string",
                    "example": "geral@empresa.com"
                },
                "portal_financas_password": {
                    "type": "string",
                    "example": "password123"
                },
                "portal_financas_user": {
                    "type": "string",
                    "example": "123456789"
                },
                "preferred_contact_hours": {
                    "type": "string",
                    "example": "9h-17h"
                },
                "preferred_format": {
                    "type": "string",
                    "example": "digital"
                },
                "ss_direct_password": {
                    "type": "string",
                    "example": "password123"
                },
                "ss_direct_user": {
                    "type": "string",
                    "example": "123456789"
                }
            }
        },
        "models.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "minLength": 6,
                    "example": "123456"
                },
                "username": {
                    "type": "string",
                    "example": "joao.silva"
                }
            }
        },
        "models.RegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "name",
                "nif",
                "password",
                "phone",
                "role",
                "status",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "joao@exemplo.com"
                },
                "name": {
                    "type": "string",
                    "minLength": 2,
                    "example": "João Silva"
                },
                "nif": {
                    "type": "string",
                    "example": "123456789"
                },
                "password": {
                    "type": "string",
                    "minLength": 6,
                    "example": "123456"
                },
                "phone": {
                    "type": "string",
                    "example": "912345678"
                },
                "role": {
                    "type": "string",
                    "enum": [
                        "client",
                        "accountant",
                        "admin"
                    ],
                    "example": "client"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "pending",
                        "approved",
                        "rejected",
                        "blocked"
                    ],
                    "example": "pending"
                },
                "username": {
                    "type": "string",
                    "example": "joao.silva"
                }
            }
        },
        "models.RegistrationRequest": {
            "type": "object",
            "properties": {
                "accounting_regime": {
                    "type": "string"
                },
                "annual_revenue": {
                    "description": "Dados operacionais",
                    "type": "number"
                },
                "approval_token": {
                    "type": "string"
                },
                "bank_name": {
                    "description": "Informação bancária",
                    "type": "string"
                },
                "bic": {
                    "type": "string"
                },
                "billing_software": {
                    "type": "string"
                },
                "business_activity": {
                    "type": "string"
                },
                "cae": {
                    "description": "Dados básicos opcionais",
                    "type": "string"
                },
                "citizen_card_expiry": {
                    "type": "string"
                },
                "citizen_card_number": {
                    "type": "string"
                },
                "company": {
                    "$ref": "#/definitions/models.Company"
                },
                "company_address": {
                    "type": "string"
                },
                "company_city": {
                    "type": "string"
                },
                "company_country": {
                    "type": "string"
                },
                "company_county": {
                    "type": "string"
                },
                "company_district": {
                    "type": "string"
                },
                "company_id": {
                    "description": "NULL até aprovação",
                    "type": "integer"
                },
                "company_name": {
                    "description": "=== DADOS DA COMPANY (armazenados até aprovação) ===\nDados básicos obrigatórios",
                    "type": "string"
                },
                "company_postal_code": {
                    "type": "string"
                },
                "corporate_object": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "date_of_birth": {
                    "description": "Dados pessoais opcionais",
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "estimated_revenue": {
                    "type": "number"
                },
                "fiscal_address": {
                    "description": "Morada fiscal",
                    "type": "string"
                },
                "fiscal_city": {
                    "type": "string"
                },
                "fiscal_county": {
                    "type": "string"
                },
                "fiscal_district": {
                    "type": "string"
                },
                "fiscal_postal_code": {
                    "type": "string"
                },
                "fixed_phone": {
                    "type": "string"
                },
                "founding_date": {
                    "type": "string"
                },
                "group_start_date": {
                    "type": "string"
                },
                "has_stock": {
                    "type": "boolean"
                },
                "iban": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "legal_form": {
                    "type": "string"
                },
                "main_clients": {
                    "type": "string"
                },
                "main_suppliers": {
                    "type": "string"
                },
                "marital_status": {
                    "type": "string"
                },
                "monthly_invoices": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "nif": {
                    "type": "string"
                },
                "nipc": {
                    "type": "string"
                },
                "number_employees": {
                    "type": "integer"
                },
                "official_email": {
                    "description": "Preferências",
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "preferred_contact_hours": {
                    "type": "string"
                },
                "preferred_format": {
                    "type": "string"
                },
                "report_frequency": {
                    "type": "string"
                },
                "request_type": {
                    "description": "new_client, existing_client",
                    "type": "string"
                },
                "review_notes": {
                    "type": "string"
                },
                "reviewed_at": {
                    "type": "string"
                },
                "reviewed_by": {
                    "type": "integer"
                },
                "reviewed_by_user": {
                    "$ref": "#/definitions/models.User"
                },
                "share_capital": {
                    "type": "number"
                },
                "status": {
                    "type": "string"
                },
                "submitted_at": {
                    "type": "string"
                },
                "tax_residence_country": {
                    "type": "string"
                },
                "trade_name": {
                    "description": "Dados completos opcionais",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user": {
                    "description": "Relacionamentos",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.User"
                        }
                    ]
                },
                "user_id": {
                    "description": "=== RELACIONAMENTOS (só existem após aprovação) ===",
                    "type": "integer"
                },
                "username": {
                    "description": "=== DADOS DO USER (armazenados até aprovação) ===\nDados pessoais obrigatórios",
                    "type": "string"
                },
                "vat_regime": {
                    "type": "string"
                }
            }
        },
        "models.RegistrationRequestDTO": {
            "type": "object",
            "required": [
                "company_name",
                "email",
                "fiscal_address",
                "fiscal_city",
                "fiscal_postal_code",
                "legal_form",
                "name",
                "nif",
                "password",
                "phone",
                "username"
            ],
            "properties": {
                "accounting_regime": {
                    "type": "string",
                    "example": "organizada"
                },
                "annual_revenue": {
                    "type": "number",
                    "example": 100000
                },
                "bank_name": {
                    "type": "string",
                    "example": "Banco Comercial Português"
                },
                "bic": {
                    "type": "string",
                    "example": "BCOMPTPL"
                },
                "billing_software": {
                    "type": "string",
                    "example": "Moloni"
                },
                "business_activity": {
                    "type": "string",
                    "example": "Consultoria em gestão"
                },
                "cae": {
                    "type": "string",
                    "example": "69200"
                },
                "citizen_card_expiry": {
                    "type": "string",
                    "example": "2030-12-31"
                },
                "citizen_card_number": {
                    "type": "string",
                    "example": "12345678"
                },
                "company_address": {
                    "type": "string",
                    "example": "Rua das Flores, 123"
                },
                "company_city": {
                    "type": "string",
                    "example": "Lisboa"
                },
                "company_country": {
                    "type": "string",
                    "example": "Portugal"
                },
                "company_county": {
                    "type": "string",
                    "example": "Lisboa"
                },
                "company_district": {
                    "type": "string",
                    "example": "Lisboa"
                },
                "company_name": {
                    "description": "=== DADOS EMPRESA ===\nObrigatórios",
                    "type": "string",
                    "example": "Silva \u0026 Associados Lda"
                },
                "company_postal_code": {
                    "type": "string",
                    "example": "1000-001"
                },
                "corporate_object": {
                    "type": "string",
                    "example": "Prestação de serviços de consultoria"
                },
                "date_of_birth": {
                    "description": "=== TODOS OS CAMPOS OPCIONAIS ===",
                    "type": "string",
                    "example": "1990-01-15"
                },
                "email": {
                    "type": "string",
                    "example": "joao@exemplo.com"
                },
                "estimated_revenue": {
                    "type": "number",
                    "example": 50000
                },
                "fiscal_address": {
                    "description": "Morada fiscal obrigatória",
                    "type": "string",
                    "example": "Rua das Flores, 123"
                },
                "fiscal_city": {
                    "type": "string",
                    "example": "Lisboa"
                },
                "fiscal_county": {
                    "type": "string",
                    "example": "Lisboa"
                },
                "fiscal_district": {
                    "type": "string",
                    "example": "Lisboa"
                },
                "fiscal_postal_code": {
                    "type": "string",
                    "example": "1000-001"
                },
                "fixed_phone": {
                    "type": "string",
                    "example": "213456789"
                },
                "founding_date": {
                    "type": "string",
                    "example": "2024-01-15"
                },
                "group_start_date": {
                    "type": "string",
                    "example": "2024-01-01"
                },
                "has_stock": {
                    "type": "boolean",
                    "example": false
                },
                "iban": {
                    "type": "string",
                    "example": "PT50000201231234567890154"
                },
                "legal_form": {
                    "type": "string",
                    "example": "Sociedade por Quotas"
                },
                "main_clients": {
                    "type": "string",
                    "example": "Cliente A, Cliente B"
                },
                "main_suppliers": {
                    "type": "string",
                    "example": "Fornecedor X, Fornecedor Y"
                },
                "marital_status": {
                    "type": "string",
                    "example": "Solteiro"
                },
                "monthly_invoices": {
                    "type": "integer",
                    "example": 10
                },
                "name": {
                    "type": "string",
                    "example": "João Silva"
                },
                "nif": {
                    "type": "string",
                    "example": "123456789"
                },
                "nipc": {
                    "description": "Opcionais",
                    "type": "string",
                    "example": "123456789"
                },
                "number_employees": {
                    "type": "integer",
                    "example": 2
                },
                "official_email": {
                    "type": "string",
                    "example": "geral@empresa.com"
                },
                "password": {
                    "type": "string",
                    "minLength": 6,
                    "example": "password123"
                },
                "phone": {
                    "type": "string",
                    "example": "912345678"
                },
                "preferred_contact_hours": {
                    "type": "string",
                    "example": "9h-17h"
                },
                "preferred_format": {
                    "type": "string",
                    "example": "digital"
                },
                "report_frequency": {
                    "type": "string",
                    "example": "mensal"
                },
                "share_capital": {
                    "type": "number",
                    "example": 5000
                },
                "tax_residence_country": {
                    "type": "string",
                    "example": "Portugal"
                },
                "trade_name": {
                    "type": "string",
                    "example": "Silva Consultoria"
                },
                "username": {
                    "description": "=== DADOS PESSOAIS ===\nObrigatórios",
                    "type": "string",
                    "example": "joao.silva"
                },
                "vat_regime": {
                    "type": "string",
                    "example": "normal"
                }
            }
        },
        "models.SuccessResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string",
                    "example": "Operação realizada com sucesso"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "models.UpdateCompanyDTO": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "example": "Rua das Flores, 123"
                },
                "city": {
                    "type": "string",
                    "example": "Lisboa"
                },
                "postal_code": {
                    "type": "string",
                    "example": "1000-001"
                },
                "trade_name": {
                    "type": "string",
                    "example": "Silva Consultoria"
                }
            }
        },
        "models.UpdateProfileDTO": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "João Silva"
                },
                "phone": {
                    "type": "string",
                    "example": "912345678"
                }
            }
        },
        "models.UpdateUserStatusDTO": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "notes": {
                    "type": "string",
                    "example": "Motivo da alteração"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "approved",
                        "rejected",
                        "blocked"
                    ],
                    "example": "approved"
                }
            }
        },
        "models.User": {
            "type": "object",
            "properties": {
                "billing_software": {
                    "type": "string"
                },
                "citizen_card_expiry": {
                    "type": "string"
                },
                "citizen_card_number": {
                    "type": "string"
                },
                "company": {
                    "description": "Relacionamentos",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Company"
                        }
                    ]
                },
                "created_at": {
                    "type": "string",
                    "example": "2023-01-01T00:00:00Z"
                },
                "date_of_birth": {
                    "description": "Dados copiados da RegistrationRequest após aprovação",
                    "type": "string"
                },
                "email": {
                    "type": "string",
                    "example": "joao@exemplo.com"
                },
                "fiscal_address": {
                    "description": "Morada fiscal completa",
                    "type": "string"
                },
                "fiscal_city": {
                    "type": "string"
                },
                "fiscal_county": {
                    "type": "string"
                },
                "fiscal_district": {
                    "type": "string"
                },
                "fiscal_postal_code": {
                    "type": "string"
                },
                "fixed_phone": {
                    "description": "Contactos adicionais",
                    "type": "string"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "marital_status": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "example": "João Silva"
                },
                "nif": {
                    "type": "string",
                    "example": "123456789"
                },
                "official_email": {
                    "description": "Acessos e credenciais (guardados encriptados)",
                    "type": "string"
                },
                "phone": {
                    "type": "string",
                    "example": "912345678"
                },
                "preferred_contact_hours": {
                    "type": "string"
                },
                "preferred_format": {
                    "description": "Preferências de comunicação",
                    "type": "string"
                },
                "registration_request": {
                    "$ref": "#/definitions/models.RegistrationRequest"
                },
                "report_frequency": {
                    "type": "string"
                },
                "reviewed_requests": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.RegistrationRequest"
                    }
                },
                "role": {
                    "type": "string",
                    "example": "client"
                },
                "status": {
                    "description": "Sempre approved quando criado",
                    "type": "string",
                    "example": "approved"
                },
                "tax_residence_country": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2023-01-01T00:00:00Z"
                },
                "username": {
                    "type": "string",
                    "example": "joao.silva"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "RV Contabilidade API",
	Description:      "Sistema de gestão contabilística com aprovação de clientes",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
